DROP TABLE BUG CASCADE CONSTRAINTS;
DROP TABLE MODUL CASCADE CONSTRAINTS;
DROP TABLE PATCH CASCADE CONSTRAINTS;
DROP TABLE TIKET CASCADE CONSTRAINTS;
DROP TABLE ZRANITELNOST CASCADE CONSTRAINTS;
DROP TABLE JAZYK CASCADE CONSTRAINTS;
DROP TABLE UZIVATEL CASCADE CONSTRAINTS;
DROP TABLE PROGRAMATOR CASCADE CONSTRAINTS;
DROP TABLE ODMENA CASCADE CONSTRAINTS;
DROP TABLE DISPONUJE_JAZYKMI CASCADE CONSTRAINTS;
DROP TABLE  CHYBA CASCADE CONSTRAINTS;

CREATE TABLE BUG
(
    ID NUMBER NOT NULL PRIMARY KEY,
    MODUL_ID NUMBER NOT NULL,
    PATCH_ID NUMBER NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE PATCH
(
    ID NUMBER NOT NULL PRIMARY KEY,
    UZIVATEL_ID NUMBER NOT NULL,
    INIT_DATE DATE NOT NULL,
    IN_RUN_DATE DATE,
    VERIFICATED NUMBER(1) NOT NULL
);

CREATE TABLE MODUL
(
    ID NUMBER NOT NULL PRIMARY KEY,
    JAZYK_ID NUMBER NOT NULL,
    PROGRAMATOR_ID NUMBER NOT NULL,
    NAME VARCHAR(255)
);

CREATE TABLE TIKET
(
    ID NUMBER NOT NULL PRIMARY KEY,
    PROGRAMATOR_ID NUMBER NOT NULL,
    UZIVATEL_ID NUMBER NOT NULL,
    TYP VARCHAR(255),
    INIT_DATE DATE NOT NULL,
    COMPLETED NUMBER(1) NOT NULL
);

CREATE TABLE JAZYK
(
    ID NUMBER NOT NULL PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE ZRANITELNOST
(
    ID NUMBER NOT NULL  PRIMARY KEY,
    SECURITY VARCHAR(255) NOT NULL
);

CREATE TABLE UZIVATEL
(
    ID NUMBER NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    AGE NUMBER NOT NULL,
    CHECK ( AGE BETWEEN 1 and 130)
);

CREATE TABLE PROGRAMATOR
(
    ID NUMBER NOT NULL PRIMARY KEY,
    SPECIALIZATION VARCHAR(255),
    STARTING_DATE DATE
);

CREATE TABLE ODMENA
(
    ID NUMBER NOT NULL PRIMARY KEY,
    UZIVATEL_ID NUMBER NOT NULL,
    DATE_OF_AWARD DATE NOT NULL,
    SIZE_OF VARCHAR(1),
    THEME VARCHAR(255),
    AMOUNT NUMBER
);

CREATE  TABLE DISPONUJE_JAZYKMI
(
    NAZOV VARCHAR(255),
    UZIVATEL_ID NUMBER NOT NULL,
    JAZYK_ID NUMBER NOT NULL
);

CREATE TABLE CHYBA
(
    BUG_ID NUMBER NOT NULL,
    TIKET_ID NUMBER NOT NULL,
    DESCRIPTION VARCHAR(255)
)

ALTER TABLE BUG ADD CONSTRAINT FK_TYKA_SA FOREIGN KEY (MODUL_ID) REFERENCES MODUL(ID);
ALTER TABLE ZRANITELNOST ADD CONSTRAINT FK_JE_ZRANITELNOST FOREIGN KEY (ID) REFERENCES BUG(ID);
ALTER TABLE PATCH ADD CONSTRAINT FK_VYDAL FOREIGN KEY (UZIVATEL_ID) REFERENCES UZIVATEL(ID);
ALTER TABLE ODMENA ADD CONSTRAINT FK_DOSTAL FOREIGN KEY (UZIVATEL_ID) REFERENCES  UZIVATEL(ID);
ALTER TABLE TIKET ADD CONSTRAINT  FK_VYTVORIL FOREIGN KEY (UZIVATEL_ID) REFERENCES UZIVATEL(ID);
ALTER TABLE TIKET ADD CONSTRAINT  FK_ZABRAL FOREIGN KEY  (PROGRAMATOR_ID) REFERENCES PROGRAMATOR(ID);
ALTER TABLE MODUL ADD CONSTRAINT  FK_JE_V_JAZYKU FOREIGN KEY (JAZYK_ID) REFERENCES JAZYK(ID);
ALTER TABLE MODUL ADD CONSTRAINT  FK_ZODPOVEDNY_ZA_MODUL FOREIGN KEY  (PROGRAMATOR_ID) REFERENCES PROGRAMATOR(ID);
ALTER TABLE DISPONUJE_JAZYKMI ADD CONSTRAINT  FK_OVLADA FOREIGN KEY (UZIVATEL_ID) REFERENCES UZIVATEL(ID);
ALTER TABLE DISPONUJE_JAZYKMI ADD CONSTRAINT  FK_NAZOV FOREIGN KEY (JAZYK_ID) REFERENCES JAZYK(ID);
ALTER TABLE CHYBA ADD CONSTRAINT  FK_OBSAHUJE FOREIGN KEY (BUG_ID) REFERENCES BUG(ID);
ALTER TABLE CHYBA ADD CONSTRAINT  FK_JE_NA_TIKETE FOREIGN KEY (TIKET_ID) REFERENCES TIKET(ID);
ALTER TABLE BUG ADD CONSTRAINT FK_OPRAVUJE FOREIGN KEY (PATCH_ID) REFERENCES PATCH(ID);

