DROP TABLE BUG CASCADE CONSTRAINTS;
DROP TABLE MODUL CASCADE CONSTRAINTS;
DROP TABLE PATCH CASCADE CONSTRAINTS;
DROP TABLE TIKET CASCADE CONSTRAINTS;
DROP TABLE ZRANITELNOST CASCADE CONSTRAINTS;
DROP TABLE JAZYK CASCADE CONSTRAINTS;
DROP TABLE UZIVATEL CASCADE CONSTRAINTS;
DROP TABLE PROGRAMATOR CASCADE CONSTRAINTS;
DROP TABLE ODMENA CASCADE CONSTRAINTS;
DROP TABLE DISPONUJE_JAZYKMI CASCADE CONSTRAINTS;
DROP TABLE CHYBA CASCADE CONSTRAINTS;
DROP SEQUENCE BUG_ID;
DROP MATERIALIZED VIEW TIKETY_UZIVATELOV;



CREATE TABLE BUG
(
    ID NUMBER PRIMARY KEY,
    MODUL_ID NUMBER NOT NULL,
    PATCH_ID NUMBER,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CHECK ( LENGTH(DESCRIPTION) > 10 ) /* describe the damn bugs! */
);

CREATE TABLE PATCH
(
    ID NUMBER GENERATED AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    UZIVATEL_ID NUMBER NOT NULL,
    INIT_DATE DATE NOT NULL,
    IN_RUN_DATE DATE,
    VERIFIED NUMBER(1) NOT NULL,
    CHECK ( VERIFIED in (0,1) )
);

CREATE TABLE MODUL
(
    ID NUMBER GENERATED AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    JAZYK_ID NUMBER NOT NULL,
    PROGRAMATOR_ID NUMBER NOT NULL,
    NAME VARCHAR(255)
);

CREATE TABLE TIKET
(
    ID NUMBER GENERATED AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    PROGRAMATOR_ID NUMBER NOT NULL,
    UZIVATEL_ID NUMBER NOT NULL,
    TYPE VARCHAR(255),
    INIT_DATE DATE NOT NULL,
    COMPLETED NUMBER(1) NOT NULL,
    CHECK ( COMPLETED in (0,1) )
);


CREATE TABLE JAZYK
(
    ID NUMBER GENERATED AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    NAME VARCHAR(255),
    CHECK ( NAME != 'HTML' )
);

CREATE TABLE ZRANITELNOST
(
    BUG_ID NUMBER NOT NULL PRIMARY KEY,
    SECURITY VARCHAR(255) NOT NULL,
    CHECK ( SECURITY in ('kriticka', 'stredne kriticka', 'nekriticka') )
);

CREATE TABLE UZIVATEL
(
    ID NUMBER GENERATED AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    AGE NUMBER NOT NULL,
    CHECK ( AGE BETWEEN 1 and 130)
);

CREATE TABLE PROGRAMATOR
(
    UZIVATEL_ID NUMBER NOT NULL PRIMARY KEY,
    SPECIALIZATION VARCHAR(255),
    STARTING_DATE DATE
);

CREATE OR REPLACE TRIGGER programator_check_date
  BEFORE INSERT OR UPDATE ON PROGRAMATOR
  FOR EACH ROW
BEGIN
  IF( :new.STARTING_DATE > CURRENT_DATE )
  THEN
    RAISE_APPLICATION_ERROR( -20002,
          'Invalid STARTING_DATE: StartingDate must be lesser than the current date. STARTING_DATE value: ' ||
          to_char( :new.STARTING_DATE, 'YYYY-MM-DD HH24:MI:SS' ) );
  END IF;
END;

CREATE TABLE ODMENA
(
    ID NUMBER GENERATED AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    UZIVATEL_ID NUMBER NOT NULL,
    DATE_OF_AWARD DATE NOT NULL,
    SIZE_OF VARCHAR(4),
    THEME VARCHAR(255),
    AMOUNT NUMBER,
    CHECK ( SIZE_OF IN ('S','M', 'L','XL','XXL','XXXL') )
);

CREATE OR REPLACE TRIGGER odmena_check_date
  BEFORE INSERT OR UPDATE ON ODMENA
  FOR EACH ROW
BEGIN
  IF( :new.DATE_OF_AWARD > CURRENT_DATE )
  THEN
    RAISE_APPLICATION_ERROR( -20003,
          'Invalid DATE_OF_AWARD: DateOfAward must be lesser than the current date. DATE_OF_AWARD value: ' ||
          to_char( :new.DATE_OF_AWARD, 'YYYY-MM-DD HH24:MI:SS' ) );
  END IF;
END;

CREATE  TABLE DISPONUJE_JAZYKMI
(
    ID NUMBER GENERATED AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    UZIVATEL_ID NUMBER NOT NULL,
    JAZYK_ID NUMBER NOT NULL
);

CREATE TABLE CHYBA
(
        ID NUMBER GENERATED AS IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    BUG_ID NUMBER NOT NULL,
    TIKET_ID NUMBER NOT NULL
);

-------4.cast-----------------------------
CREATE SEQUENCE BUG_ID;

CREATE OR REPLACE TRIGGER generate_id
    BEFORE INSERT ON BUG
    FOR EACH ROW
    WHEN ( NEW.ID IS NULL )
    BEGIN
        :NEW.ID := BUG_ID.nextval;
    end;

CREATE OR REPLACE TRIGGER tiket_check_date
  BEFORE INSERT OR UPDATE ON TIKET
  FOR EACH ROW
BEGIN
  IF( :new.INIT_DATE > CURRENT_DATE )
  THEN
    RAISE_APPLICATION_ERROR( -20001,
          'Invalid INIT_DATE: InitDate must be lesser than the current date. INIT_DATE value: ' ||
          to_char( :new.INIT_DATE, 'YYYY-MM-DD HH24:MI:SS' ) );
  END IF;
END;
------------------------------------------

ALTER TABLE BUG ADD CONSTRAINT FK_TYKA_SA FOREIGN KEY (MODUL_ID) REFERENCES MODUL(ID);
ALTER TABLE ZRANITELNOST ADD CONSTRAINT FK_ZRAN_JE_BUG FOREIGN KEY (BUG_ID) REFERENCES BUG(ID);
ALTER TABLE PATCH ADD CONSTRAINT FK_VYDAL FOREIGN KEY (UZIVATEL_ID) REFERENCES UZIVATEL(ID);
ALTER TABLE ODMENA ADD CONSTRAINT FK_DOSTAL FOREIGN KEY (UZIVATEL_ID) REFERENCES  UZIVATEL(ID);
ALTER TABLE TIKET ADD CONSTRAINT  FK_VYTVORIL FOREIGN KEY (UZIVATEL_ID) REFERENCES UZIVATEL(ID);
ALTER TABLE TIKET ADD CONSTRAINT  FK_ZABRAL FOREIGN KEY  (PROGRAMATOR_ID) REFERENCES PROGRAMATOR(UZIVATEL_ID);
ALTER TABLE MODUL ADD CONSTRAINT  FK_JE_V_JAZYKU FOREIGN KEY (JAZYK_ID) REFERENCES JAZYK(ID);
ALTER TABLE MODUL ADD CONSTRAINT  FK_ZODPOVEDNY_ZA_MODUL FOREIGN KEY  (PROGRAMATOR_ID) REFERENCES UZIVATEL(ID);
ALTER TABLE DISPONUJE_JAZYKMI ADD CONSTRAINT  FK_OVLADA FOREIGN KEY (UZIVATEL_ID) REFERENCES UZIVATEL(ID);
ALTER TABLE DISPONUJE_JAZYKMI ADD CONSTRAINT  FK_NAZOV FOREIGN KEY (JAZYK_ID) REFERENCES JAZYK(ID);
ALTER TABLE CHYBA ADD CONSTRAINT  FK_OBSAHUJE FOREIGN KEY (BUG_ID) REFERENCES BUG(ID);
ALTER TABLE CHYBA ADD CONSTRAINT  FK_JE_NA_TIKETE FOREIGN KEY (TIKET_ID) REFERENCES TIKET(ID);
ALTER TABLE BUG ADD CONSTRAINT FK_OPRAVUJE FOREIGN KEY (PATCH_ID) REFERENCES PATCH(ID);
ALTER TABLE PROGRAMATOR ADD CONSTRAINT FK_PROG_JE_UZI FOREIGN KEY (UZIVATEL_ID) REFERENCES UZIVATEL(ID);

INSERT INTO UZIVATEL(NAME, AGE) VALUES ('Tomas Holly', 25);
INSERT INTO UZIVATEL(NAME, AGE) VALUES ('Adam Zavodsky', 34);
INSERT INTO UZIVATEL(NAME, AGE) VALUES ('Ivan Zavodsky', 32);
INSERT INTO UZIVATEL(NAME, AGE) VALUES ('Jozef Ignac Bajza', 40);
INSERT INTO UZIVATEL(NAME, AGE) VALUES ('Tomas Petrovicky', 28);
INSERT INTO UZIVATEL(NAME, AGE) VALUES ('Ladislav Vojtech', 22);

INSERT INTO PROGRAMATOR(UZIVATEL_ID, SPECIALIZATION, STARTING_DATE) VALUES (1, 'Junior Database Engineer', DATE '2019-05-03');
INSERT INTO PROGRAMATOR(UZIVATEL_ID, SPECIALIZATION, STARTING_DATE) VALUES (2, 'Senior Backend Engineer', DATE '2019-02-23');
INSERT INTO PROGRAMATOR(UZIVATEL_ID, SPECIALIZATION, STARTING_DATE) VALUES (3, 'Senior Frontend Engineer', DATE '2019-03-02');

INSERT INTO JAZYK(NAME) VALUES ('SQL');
INSERT INTO JAZYK(NAME) VALUES ('C#');
INSERT INTO JAZYK(NAME) VALUES ('Java');
INSERT INTO JAZYK(NAME) VALUES ('Javascript');
INSERT INTO JAZYK(NAME) VALUES ('Python');

INSERT INTO DISPONUJE_JAZYKMI(UZIVATEL_ID, JAZYK_ID) VALUES (1, 1);
INSERT INTO DISPONUJE_JAZYKMI(UZIVATEL_ID, JAZYK_ID) VALUES (2, 1);
INSERT INTO DISPONUJE_JAZYKMI(UZIVATEL_ID, JAZYK_ID) VALUES (2, 2);
INSERT INTO DISPONUJE_JAZYKMI(UZIVATEL_ID, JAZYK_ID) VALUES (2, 3);
INSERT INTO DISPONUJE_JAZYKMI(UZIVATEL_ID, JAZYK_ID) VALUES (3, 4);
INSERT INTO DISPONUJE_JAZYKMI(UZIVATEL_ID, JAZYK_ID) VALUES (3, 5);
INSERT INTO DISPONUJE_JAZYKMI(UZIVATEL_ID, JAZYK_ID) VALUES (4, 2);
INSERT INTO DISPONUJE_JAZYKMI(UZIVATEL_ID, JAZYK_ID) VALUES (4, 5);
INSERT INTO DISPONUJE_JAZYKMI(UZIVATEL_ID, JAZYK_ID) VALUES (2, 5);
INSERT INTO DISPONUJE_JAZYKMI(UZIVATEL_ID, JAZYK_ID) VALUES (5, 5);
INSERT INTO DISPONUJE_JAZYKMI(UZIVATEL_ID, JAZYK_ID) VALUES (6, 4);

INSERT INTO ODMENA(UZIVATEL_ID, DATE_OF_AWARD, SIZE_OF, THEME, AMOUNT) VALUES (4, DATE '2019-8-13', 'L', 'Superhero Red', null);
INSERT INTO ODMENA(UZIVATEL_ID, DATE_OF_AWARD, SIZE_OF, THEME, AMOUNT) VALUES (5, DATE '2019-9-12', null, null, 500);
INSERT INTO ODMENA(UZIVATEL_ID, DATE_OF_AWARD, SIZE_OF, THEME, AMOUNT) VALUES (5, DATE '2019-10-1', 'XL', 'SuperHero Grey', null);
INSERT INTO ODMENA(UZIVATEL_ID, DATE_OF_AWARD, SIZE_OF, THEME, AMOUNT) VALUES (5, DATE '2019-10-24', null, null, 350);
INSERT INTO ODMENA(UZIVATEL_ID, DATE_OF_AWARD, SIZE_OF, THEME, AMOUNT) VALUES (4, DATE '2019-10-27', 'L', 'Company Logo White', null);

INSERT INTO MODUL(JAZYK_ID, PROGRAMATOR_ID, NAME) VALUES (1, 1, 'Ulozenie dat');
INSERT INTO MODUL(JAZYK_ID, PROGRAMATOR_ID, NAME) VALUES (1, 1, 'Zaloha');
INSERT INTO MODUL(JAZYK_ID, PROGRAMATOR_ID, NAME) VALUES (2, 2, 'Synchronizacia serverov');
INSERT INTO MODUL(JAZYK_ID, PROGRAMATOR_ID, NAME) VALUES (3, 2, 'Klientska aplikacia');
INSERT INTO MODUL(JAZYK_ID, PROGRAMATOR_ID, NAME) VALUES (4, 3, 'Prihlasenie a registracia');
INSERT INTO MODUL(JAZYK_ID, PROGRAMATOR_ID, NAME) VALUES (4, 3, 'Uzivatelske rozhranie aplikacie');

INSERT INTO PATCH(UZIVATEL_ID, INIT_DATE, IN_RUN_DATE, VERIFIED) VALUES (1, DATE '2019-8-5', DATE '2019-8-8', 1);
INSERT INTO PATCH(UZIVATEL_ID, INIT_DATE, IN_RUN_DATE, VERIFIED) VALUES (2, DATE '2019-9-1', DATE '2019-9-2', 1);
INSERT INTO PATCH(UZIVATEL_ID, INIT_DATE, IN_RUN_DATE, VERIFIED) VALUES (2, DATE '2019-9-3', DATE '2019-9-3', 1);
INSERT INTO PATCH(UZIVATEL_ID, INIT_DATE, IN_RUN_DATE, VERIFIED) VALUES (2, DATE '2019-10-10', DATE '2019-10-12', 0);

INSERT INTO BUG(MODUL_ID, PATCH_ID, DESCRIPTION) VALUES (1, 1, 'Aplikacia neulozi udaje z registracie');
INSERT INTO BUG(MODUL_ID, PATCH_ID, DESCRIPTION) VALUES (1, 1, 'Dlho sa nacitavaju udaje z databazy');
INSERT INTO BUG(MODUL_ID, PATCH_ID, DESCRIPTION) VALUES (6, null, 'Preblikava sa tlacidlo na registraciu');
INSERT INTO BUG(MODUL_ID, PATCH_ID, DESCRIPTION) VALUES (6, null, 'Prilis maly text vo formoch');
INSERT INTO BUG(MODUL_ID, PATCH_ID, DESCRIPTION) VALUES (5, 2, 'Po prihlaseni sa nenacita aplikacia');
INSERT INTO BUG(MODUL_ID, PATCH_ID, DESCRIPTION) VALUES (4, 2, 'Prihlasi ma so starym heslom');
INSERT INTO BUG(MODUL_ID, PATCH_ID, DESCRIPTION) VALUES (4, 3, 'Aplikacia prestane reagovat pri scrollovani v nastaveniach');
INSERT INTO BUG(MODUL_ID, PATCH_ID, DESCRIPTION) VALUES (3, 4, 'Pre serverovy counter ukazuje cudzie hodnoty');
INSERT INTO BUG(MODUL_ID, PATCH_ID, DESCRIPTION) VALUES (3, 4, 'Po automatickom odhlaseni bez refreshu stale ukazuje data zo serverov');

INSERT INTO TIKET(PROGRAMATOR_ID, UZIVATEL_ID, TYPE, INIT_DATE, COMPLETED) VALUES (1, 4, 'Po zacati pouzivania aplikacie sme narazili na par problemov. Prosim pozrite sa na to.', DATE '2019-8-4', 1);
INSERT INTO TIKET(PROGRAMATOR_ID, UZIVATEL_ID, TYPE, INIT_DATE, COMPLETED) VALUES (2, 5, 'Nas zamestnanec ma problem s pouzivanim vasho produktu, prosime o co najskorsiu napravu', DATE '2019-8-25', 1);
INSERT INTO TIKET(PROGRAMATOR_ID, UZIVATEL_ID, TYPE, INIT_DATE, COMPLETED) VALUES (2, 5, 'Posielam vam par bugov, aplikacia je pre mna v momentalnom stave nepouzitelna.', DATE '2019-9-3', 1);
INSERT INTO TIKET(PROGRAMATOR_ID, UZIVATEL_ID, TYPE, INIT_DATE, COMPLETED) VALUES (2, 5, 'Zdravim, nasiel som nejake chyby v programe', DATE '2019-10-1', 0);

INSERT INTO ZRANITELNOST(BUG_ID, SECURITY) VALUES (6, 'nekriticka');
INSERT INTO ZRANITELNOST(BUG_ID, SECURITY) VALUES (8, 'kriticka');
INSERT INTO ZRANITELNOST(BUG_ID, SECURITY) VALUES (9, 'stredne kriticka');

INSERT INTO CHYBA(BUG_ID, TIKET_ID) VALUES (1, 1);
INSERT INTO CHYBA(BUG_ID, TIKET_ID) VALUES (2, 1);
INSERT INTO CHYBA(BUG_ID, TIKET_ID) VALUES (3, 1);
INSERT INTO CHYBA(BUG_ID, TIKET_ID) VALUES (4, 2);
INSERT INTO CHYBA(BUG_ID, TIKET_ID) VALUES (5, 3);
INSERT INTO CHYBA(BUG_ID, TIKET_ID) VALUES (6, 3);
INSERT INTO CHYBA(BUG_ID, TIKET_ID) VALUES (7, 4);
INSERT INTO CHYBA(BUG_ID, TIKET_ID) VALUES (8, 4);
INSERT INTO CHYBA(BUG_ID, TIKET_ID) VALUES (9, 4);

COMMIT;


------------------------------------------------------------------------------------------------------
--Zistí, ktorý užívateľ napísal aký tiket
SELECT UZIVATEL.NAME as MENO_UZIVATELA,  T.TYPE as TYP_TIKETU
       FROM UZIVATEL
            JOIN TIKET T on UZIVATEL.ID = T.UZIVATEL_ID;

--Zisté zapezpečenie konkrétneho bugu
SELECT BUG.DESCRIPTION as SPECIFIKACIA_BUGU, Z.SECURITY as ZABEZPECENIE_BUGU
       FROM BUG
            JOIN ZRANITELNOST Z on BUG.ID = Z.BUG_ID;

-- Zistí, ktorý patch bol použitý opravuje bug týkajúci sa uršitého modulu
SELECT BUG.DESCRIPTION as SPECIFIKACIA_BUGU, P.ID as ID_PATCHU, M.NAME as MODUL
       FROM BUG
        JOIN PATCH P on BUG.PATCH_ID = P.ID
        JOIN MODUL M on BUG.MODUL_ID = M.ID;

--Počet modulov v danom jazyku
SELECT COUNT(MODUL.NAME) as POCET_MODULOV, J.NAME as MENO_JAZYKA
    FROM MODUL
        JOIN JAZYK J on MODUL.JAZYK_ID = J.ID
GROUP BY J.NAME
ORDER BY J.NAME;

--Koľko odmien získal daný užívateľ, zoradí od najväčšieho čísla
SELECT UZIVATEL.NAME as MENO_UZIVATELA, COUNT(O.ID) as ODMENA
    FROM UZIVATEL
        JOIN ODMENA O on UZIVATEL.ID = O.UZIVATEL_ID
GROUP BY UZIVATEL.NAME
ORDER BY COUNT(O.ID) DESC;

--Ukáže popis bugov, kde je zraniteľnosť kritická
SELECT BUG.DESCRIPTION as SPECIFIKACIA_BUGU
    FROM BUG
    WHERE BUG.ID IN
    (SELECT  ZRANITELNOST.BUG_ID
        FROM ZRANITELNOST WHERE ZRANITELNOST.SECURITY = 'kriticka');

--Ukáže všetkých programátorov, ktorí majú zabraný nejaký tiket
SELECT NAME as MENO
    FROM UZIVATEL
    WHERE EXISTS (SELECT ID FROM TIKET WHERE TIKET.PROGRAMATOR_ID = UZIVATEL.ID)

---------------4.cast----------------------
-------------PROCEDURY---------------------
------zisti, tikety daneho uzivatela-------
CREATE OR REPLACE PROCEDURE tiket_uzivatela(UZIVATEL_MENO UZIVATEL.NAME%TYPE) AS
    CURSOR PRINT IS SELECT UZIVATEL.NAME AS MENO_UZIVATELA, T.TYPE AS TYP_TIKETU
    FROM UZIVATEL JOIN TIKET T on UZIVATEL.ID = T.UZIVATEL_ID
    WHERE UZIVATEL.NAME = UZIVATEL_MENO;

        ROW_TO_PRINT PRINT%ROWTYPE;

    BEGIN
        OPEN PRINT;
        FETCH PRINT INTO ROW_TO_PRINT;
        IF PRINT%NOTFOUND THEN
            RAISE NO_DATA_FOUND;
        end if;
        WHILE PRINT%FOUND LOOP
            DBMS_OUTPUT.PUT_LINE('User: ' || ROW_TO_PRINT.MENO_UZIVATELA || '->' || ROW_TO_PRINT.TYP_TIKETU );
            FETCH PRINT INTO ROW_TO_PRINT;
            end loop;
        CLOSE PRINT;

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('User: ' || UZIVATEL_MENO || ' did not create any ticket');
    end;

CALL TIKET_UZIVATELA('Tomas Petrovicky');
CALL TIKET_UZIVATELA('Tomas Holly');


-----pocet modulov v danom jazyku-----

CREATE OR REPLACE PROCEDURE moduly_jazyka(JAZYK_NAZOV JAZYK.NAME%TYPE) AS
    CURSOR PRINT IS SELECT M.NAME AS MENO_MODULU, JAZYK.NAME AS MENO_JAZYKA
    FROM JAZYK JOIN MODUL M on JAZYK.ID = M.JAZYK_ID
    WHERE JAZYK.NAME = JAZYK_NAZOV;

        ROW_TO_PRINT PRINT%ROWTYPE;
    pocet NUMBER;
    BEGIN
        pocet := 0;
        OPEN PRINT;
        FETCH PRINT INTO ROW_TO_PRINT;
        IF PRINT%NOTFOUND THEN
            RAISE NO_DATA_FOUND;
        end if;
        WHILE PRINT%FOUND LOOP
            pocet := pocet + 1;
            FETCH PRINT INTO ROW_TO_PRINT;
            end loop;
        DBMS_OUTPUT.PUT_LINE('Jazyk: ' || ROW_TO_PRINT.MENO_JAZYKA || '->' || pocet);
        CLOSE PRINT;

        EXCEPTION
        WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE(JAZYK_NAZOV || 'NEMA ZIADNY MODUL');
    end;

CALL MODULY_JAZYKA('C#');
CALL MODULY_JAZYKA('T-SQL');

--------------INDEXY---------------
EXPLAIN PLAN FOR
    SELECT MODUL.NAME AS MENO_MODULU, COUNT(B.ID) AS BUG
    FROM MODUL JOIN BUG B on MODUL.ID = B.MODUL_ID
    GROUP BY MODUL.NAME;

SELECT PLAN_TABLE_OUTPUT FROM TABLE( DBMS_XPLAN.DISPLAY());

CREATE INDEX modul_index ON BUG(MODUL_ID);

EXPLAIN PLAN FOR
    SELECT MODUL.NAME as MENO_MODULU, COUNT(B.ID) AS BUG
    FROM MODUL JOIN BUG B on MODUL.ID = B.MODUL_ID
    GROUP BY MODUL.NAME;

SELECT PLAN_TABLE_OUTPUT FROM TABLE( DBMS_XPLAN.DISPLAY());

------------GRANTS FOR XKENDE01----------------

GRANT ALL ON BUG TO XKENDE01;
GRANT ALL ON PATCH TO XKENDE01;
GRANT ALL ON TIKET TO XKENDE01;
GRANT ALL ON ZRANITELNOST TO XKENDE01;
GRANT ALL ON JAZYK TO XKENDE01;
GRANT ALL ON UZIVATEL TO XKENDE01;
GRANT ALL ON PROGRAMATOR TO XKENDE01;
GRANT ALL ON ODMENA TO XKENDE01;
GRANT ALL ON DISPONUJE_JAZYKMI TO XKENDE01;
GRANT ALL ON CHYBA TO XKENDE01;
GRANT EXECUTE ON MODULY_JAZYKA TO XKENDE01;
GRANT EXECUTE ON TIKET_UZIVATELA TO XKENDE01;

------------MATERIALIZED VIEW-----------------
CREATE MATERIALIZED VIEW TIKETY_UZIVATELOV NOLOGGING CACHE BUILD IMMEDIATE REFRESH ON COMMIT AS
SELECT XDURIS05.UZIVATEL.NAME as MENO_UZIVATELA, T.TYPE as TYP_TIKETU
       FROM XDURIS05.UZIVATEL
            JOIN XDURIS05.TIKET T on XDURIS05.UZIVATEL.ID = T.UZIVATEL_ID;
GRANT ALL ON TIKETY_UZIVATELOV TO XKENDE01;

--Demonstracia funkcnosti materializovaneho pohladu--
SELECT * FROM TIKETY_UZIVATELOV; --vypise aktualny stav materializovaneho pohladu
INSERT INTO XDURIS05.UZIVATEL(NAME, AGE) VALUES ('Marian Testovy', 21); --vlozenie noveho uzivatela
INSERT INTO XDURIS05.TIKET(PROGRAMATOR_ID, UZIVATEL_ID, TYPE, INIT_DATE, COMPLETED) VALUES (1, 7, 'Posielam bugy v materializovanom pohlade', DATE '2019-9-20', 1); --vlozenie testovacieho tiketu pre prave vlozeneho uzivatela
SELECT * FROM TIKETY_UZIVATELOV; --pohlad je stale v povodnom stave
COMMIT;
SELECT * FROM TIKETY_UZIVATELOV; --po commite vidno zmeny v pohlade